# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  # vmImage: ubuntu-latest
  name: 'MyAzureAgent'

steps:
- task: JavaToolInstaller@0
  inputs:
    mavenPomFile: 'C:/AzureAgent/vsts-agent-win-x64-2.213.2/_work/1\s/com.automation/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    versionSpec: '1.8'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: Cache
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
